name: Keboola Component Deployment Pipeline
on: [ push ]
concurrency: ci-${{ github.ref }} # to avoid tag collisions in the ECR
env:
  DOCKERHUB_USER: "keboolabot"
  KBC_DEVELOPERPORTAL_APP: "kds-team.app-flow-trigger-tracker"
  KBC_DEVELOPERPORTAL_VENDOR: "kds-team"
  KBC_DEVELOPERPORTAL_USERNAME: "kds-team+github"

  # to be set in repository secrets:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} # required for pushing to ECR
  # KBC_STORAGE_TOKEN: ${{ secrets.KBC_STORAGE_TOKEN }} # required for running KBC tests (optional)
  # KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}

  # Test KBC project: https://connection.keboola.com/admin/projects/5415
  KBC_TEST_PROJECT_CONFIGS: "" # space separated list of config ids (optional)

jobs:
  determine_environment:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      ACTUAL_BRANCH: ${{ github.ref }}
      HEAD_REF: ${{ github.head_ref }}
      REF_NAME: ${{ github.ref_name }}
      BASE_REF: ${{ github.base_ref }}
      EVENT_REF: ${{ github.event.ref }}
    outputs:
      app_image_tag: ${{ steps.tag.outputs.app_image_tag }}
      is_semantic_tag: ${{ steps.tag.outputs.is_semantic_tag }}
      is_default_branch: ${{ steps.branch.outputs.is_default_branch }}
      is_deploy_ready: ${{ steps.deploy_ready.outputs.is_deploy_ready }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch_name
        run: |
          echo "Branch name is $(git rev-parse --abbrev-ref $(git rev-list -n 1 ${{ github.ref }}))"
          raw=$(git branch -r --contains ${{ github.ref }})
          branch="$(echo ${raw//origin\//} | tr -d '\n')"
          echo "{name}=branch" >> $GITHUB_OUTPUT
          echo "Branches where this tag exists : $branch."

      - name: Print branch name
        run: echo "Branch for tag is ${{ steps.branch_name.outputs.branch_name }}"

      - name: Is current branch the default branch
        id: branch
        run: |
          echo "'${{ env.HEAD_REF }}' - '${{ env.REF_NAME }}' - '${{ env.BASE_REF }}' - '${{ env.EVENT_REF }}'"
          echo "default_branch is '${{ env.DEFAULT_BRANCH }}' and actual_branch is '${{ env.ACTUAL_BRANCH }}'"
          actual_branch_name="${{ env.ACTUAL_BRANCH }}"
          if [ "${{ env.DEFAULT_BRANCH }}" = "${actual_branch_name/#refs\/tags\//}" ]; then
              IS_DEFAULT_BRANCH=true
          else
              IS_DEFAULT_BRANCH=false
          fi
          echo "is_default_branch=$IS_DEFAULT_BRANCH" >> $GITHUB_OUTPUT

      - name: Set image tag
        id: tag
        run: |
          TAG="${GITHUB_REF##*/}"
          IS_SEMANTIC_TAG=$(echo "$TAG" | grep -q '^v\?[0-9]\+\.[0-9]\+\.[0-9]\+$' && echo true || echo false)
          echo "Tag = '$TAG', is semantic tag = '$IS_SEMANTIC_TAG'"
          echo "is_semantic_tag=$IS_SEMANTIC_TAG" >> $GITHUB_OUTPUT
          echo "app_image_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Is ready to deploy
        id: deploy_ready
        run: |
          if [[ "${{ steps.branch.outputs.is_default_branch }}" == 'true' \
            && "${{ env.ACTUAL_BRANCH }}" == refs/tags/* \
            && "${{ steps.tag.outputs.is_semantic_tag }}" == 'true' ]]; then
              IS_DEPLOY_READY='true'
          else
              IS_DEPLOY_READY='false'
          fi
          echo "Deploy Ready: $IS_DEPLOY_READY"
          echo "is_deploy_ready=$IS_DEPLOY_READY" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs:
      - determine_environment
    env:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker login
        if: env.DOCKERHUB_TOKEN
        run: docker login --username "${{ env.DOCKERHUB_USER }}" --password "${{ env.DOCKERHUB_TOKEN }}"

      - name: Build image
        run: docker build -t "${{ env.KBC_DEVELOPERPORTAL_APP }}" .

      - name: Push image to ECR
        uses: keboola/action-push-to-ecr@master
        with:
          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP }}
          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ needs.determine_environment.outputs.app_image_tag }}
          push_latest: ${{ needs.determine_environment.is_semantic_tag }}
          source_image: ${{ env.KBC_DEVELOPERPORTAL_APP }}

  tests:
    runs-on: ubuntu-latest
    needs:
      - determine_environment
      - build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Pull image from ECR
        uses: keboola/action-pull-from-ecr@master
        with:
          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP }}
          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ needs.determine_environment.outputs.app_image_tag }}
          target_image: ${{ env.KBC_DEVELOPERPORTAL_APP}}
          tag_as_latest: true

      - name: Run tests
        run: |
          docker run ${{ env.KBC_DEVELOPERPORTAL_APP }} flake8 . --config=flake8.cfg
          echo "Running unit-tests..."
          docker run ${{ env.KBC_DEVELOPERPORTAL_APP }} python -m unittest discover

  tests-kbc:
    env:
      KBC_TEST_PROJECT_CONFIGS: ${{ vars.KBC_TEST_PROJECT_CONFIGS }}
      KBC_STORAGE_TOKEN: ${{ secrets.KBC_STORAGE_TOKEN }}
    needs:
      - determine_environment
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Run KBC test jobs
        if: ${{ env.KBC_TEST_PROJECT_CONFIGS != '' }} && ${{ env.KBC_STORAGE_TOKEN != '' }}
        uses: keboola/action-run-configs-parallel@master
        with:
          token: ${{ secrets.KBC_STORAGE_TOKEN }}
          componentId: ${{ env.KBC_DEVELOPERPORTAL_APP }}
          tag: ${{ needs.determine_environment.outputs.app_image_tag }}
          configs: ${{ env.KBC_TEST_PROJECT_CONFIGS }}

  deploy:
    env:
      KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
    needs:
      - determine_environment
      - build
      - tests
      - tests-kbc
    if: needs.determine_environment.outputs.is_deploy_ready == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Set tag in the Developer Portal
        uses: keboola/action-set-tag-developer-portal@master
        with:
          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP }}
          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ needs.determine_environment.outputs.app_image_tag }}

  update_developer_portal_properties:
    env:
      KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
      IS_DEPLOY_READY: ${{ needs.determine_environment.outputs.is_deploy_ready }}
    needs:
      - determine_environment
      - build
      - tests
      - tests-kbc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update developer portal properties
        run: |
          chmod +x scripts/developer_portal/*.sh
          scripts/developer_portal/update_properties.sh
